var tips = [
	{main: "Check faucets and pipes for leaks",
	longerDesciption: "A small drip from a worn faucet washer can waste 20 gallons of water per day. Larger leaks can waste hundreds of gallons"},
	{main: "Don't use the toilet as a trashcan",
	longerDesciption: "Every time you flush a facial tissue or other small bit of trash, five to seven gallons of water is wasted"},
	{main: "Check your toilets for leaks",
	longerDesciption: "Put a little food coloring in your toilet tank. If, without flushing, the color begins to appear in the bowl within 30 minutes, you have a leak that should be repaired immediately. Most replacement parts are inexpensive and easy to install"},
	{main: "Use your water meter to check for hidden water leaks",
	longerDesciption: "Read the house water meter before and after a two-hour period when no water is being used. If the meter does not read exactly the same, there is a leak"},
	{main: "Put plastic bottles or float boosters in your toilet tank",
	longerDesciption: "To cut down on water waste, put an inch or two of sand or pebbles inside each of two plastic bottles to weigh them down. Fill the bottles with water, screw the lids on, and put them in your toilet tank, safely away from the operating mechanisms. Or, buy an inexpensive tank bank or float booster. This may save ten or more gallons of water per day"},
	{main: "Insulate your water pipes",
	longerDesciption: "It's easy and inexpensive to insulate your water pipes with pre-slit foam pipe insulation. You'll get hot water faster plus avoid wasting water while it heats up."},
	{main: "Take shorter showers",
	longerDesciption: "One way to cut down on water use is to turn off the shower after soaping up, then turn it back on to rinse. A four-minute shower uses approximately 20 to 40 gallons of water"},
	{main: "Turn off the water after you wet your toothbrush",
	longerDesciption: "There is no need to keep the water running while brushing your teeth. Just wet your brush and fill a glass for mouth rinsing"},
	{main: "Use your dishwasher and clothes washer for only full loads",
	longerDesciption: "Automatic dishwashers and clothes washers should be fully loaded for optimum water conservation. Most makers of dishwashing soap recommend not pre-rinsing dishes which is a big water savings. With clothes washers, avoid the permanent press cycle, which uses an added 20 liters (5 gallons) for the extra rinse. For partial loads, adjust water levels to match the size of the load. Replace old clothes washers. New Energy Star rated washers use 35 - 50% less water and 50% less energy per load. If you're in the market for a new clothes washer, consider buying a water-saving frontload washer"},
	{main: "Minimize use of kitchen sink garbage disposal units",
	longerDesciption: "In-sink 'garburators' require lots of water to operate properly, and also add considerably to the volume of solids in a septic tank which can lead to maintenance problems. Start a compost pile as an alternate method of disposing food waste"},
	{main: "When washing dishes by hand, don't leave the water running for rinsing",
	longerDesciption: "If you have a double-basin, fill one with soapy water and one with rinse water. If you have a single-basin sink, gather washed dishes in a dish rack and rinse them with a spray device or a panful of hot water. Dual-swivel aerators are available to make this easier. If using a dishwasher, there is usually no need to pre-rinse the dishes"},
	{main: "Don't let the faucet run while you clean vegetables",
	longerDesciption: "Just rinse them in a stoppered sink or a pan of clean water. Use a dual-setting aerator"},
	{main: "Keep a bottle of drinking water in the fridge",
	longerDesciption: "Running tap water to cool it off for drinking water is wasteful. Store drinking water in the fridge in a safe drinking bottle. If you are filling water bottles to bring along on outdoor hikes, consider buying a LifeStraw personal water filter which enables users to drink water safely from rivers or lakes or any available body of water"},
	{main: "Plant drought-resistant lawns, shrubs and plants",
	longerDesciption: "If you are planting a new lawn, or overseeding an existing lawn, use drought-resistant grasses such as the new "Eco-Lawn". Many beautiful shrubs and plants thrive with far less watering than other species. Replace herbaceous perennial borders with native plants. Native plants will use less water and be more resistant to local plant diseases. Consider applying the principles of xeriscape for a low-maintenance, drought resistant yard. Plant slopes with plants that will retain water and help reduce runoff. Group plants according to their watering needs"},
	{main: "Put a layer of mulch around trees and plants",
	longerDesciption: "Mulch will slow evaporation of moisture while discouraging weed growth. Adding 2 - 4 inches of organic material such as compost or bark mulch will increase the ability of the soil to retain moisture. Press the mulch down around the dripline of each plant to form a slight depression which will prevent or minimize water runoff"},
	{main: "Don't water the gutter",
	longerDesciption: "Position your sprinklers so water lands on the lawn or garden, not on paved areas. Also, avoid watering on windy days"},
	{main: "Water your lawn only when it needs it",
	longerDesciption: "A good way to see if your lawn needs watering is to step on the grass. If it springs back up when you move, it doesn't need water. If it stays flat, the lawn is ready for watering. Letting the grass grow taller (to 3 inches) will also promote water retention in the soil. Most lawns only need about 1 inch of water each week. During dry spells, you can stop watering altogether and the lawn will go brown and dormant. Once cooler weather arrives, the morning dew and rainfall will bring the lawn back to its usual vigor. This may result in a brown summer lawn, but it saves a lot of water"},
	{main: "Water during the early parts of the day; avoid watering when it's windy",
	longerDesciption: "Early morning is generally better than dusk since it helps prevent the growth of fungus. Early watering, and late watering, also reduce water loss to evaporation. Watering early in the day is also the best defense against slugs and other garden pests. Try not to water when it's windy - wind can blow sprinklers off target and speed evaporation"}
];




